name: Script Checking

on:
  pull_request:
    branches: [main] # Replace 'main' with your main branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - run: npm install -g pnpm
      - name: Determine pnpm store path
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
      - uses: actions/cache@v3
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
            ${{ runner.os }}-pnpm-store-
            ${{ runner.os }}-pnpm-
      - name: PNPM Install
        run: pnpm install
      - name: Typescript Checking
        run: |
          npx tsc
          exit_code=$?
          if [ $exit_code -ne 0 ]; then
            echo "Typescript errors found!"
            exit $exit_code
          fi
